name: VictoriaMetrics
version: "1.148.0-pr83.1"
slug: victoria_metrics
description: Time Series Database for long term storage as replacement for Prometheus, InfluxDB or Graphite
webui: "http://[HOST]:[PORT:8428]/"
ingress: true
ingress_port: 8428
ingress_entry: /vmui
# host_network: true
ports:
  8428/tcp: 8428
  2003/tcp: null
ports_description:
  2003/tcp: Extra connection
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
#  - i386
init: false
backup: hot
backup_pre: /start-victoria-metrics backup
backup_exclude:
  - /data/victoria-metrics-data
  - /data/victoria-metrics-data/**
map:
  - share:rw
  - ssl
  - addon_config
options:
  retention: "99y"
  additionalArguments: ""
  enableHTTPAuth: false
  username: ""
  password: ""
  enablePrometheusScrape: false
  prometheusScrapeHTTPS: false
  prometheusScrapeInterval: "20s"
  prometheusScrapeTimeout: "15s"
  longelivedToken: ""
  homeassistantUrl: ""
  backupToShare: false
schema:
  retention: "str?"
  additionalArguments: "str?"
  enableHTTPAuth: bool
  username: "str?"
  password: "password?"
  enablePrometheusScrape: bool
  prometheusScrapeHTTPS: bool
  prometheusScrapeInterval: "str?"
  prometheusScrapeTimeout: "str?"
  longelivedToken: "password?"
  homeassistantUrl: "str?"
  backupToShare: bool
